---

- name: Configure gerty
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Install pacman packages
      ansible.builtin.import_tasks:
        file: tasks/install_packages.yml

...
